### ISSUE TITLE
Failed to build with Carthage for iOS platform

### ISSUE THREAD

**Issue by 0xkalinowski** [duosecurity/duo_api_swift#8]
*** Skipped building duo_api_swift due to the error:
Dependency "duo_api_swift" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/duosecurity/duo_api_swift/issues/new

Is is correct that this framework is available only for macOS? How I can use it with iOS?

**Comment by gao-sun** [comment]
You can use `carthage update duo_api_swift` to build a general version. Anyway it's likely you'll fail too since the package uses swift 3.0. I was trying to build and saw the error in the build output:

```
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'DuoAPISwift' from project 'DuoAPISwift')
```

Unfortunately the author @futureimperfect left DUO so you can try to call DUO APIs by yourself. It won't be hard if your project already have a RESTful API handler. Cheers.

**Comment by gao-sun** [comment]
Just a reminder: you should NOT use this package in iOS since the secret key should be stored in the server side.

**Comment by 0xkalinowski** [comment]
@gao-sun actually I've made my own fork of this repo and made build for iOS platform, which we are successfully using in project:)
